// Auto-generated by test_cov. Do not edit by hand.

import 'features/auth/domain/usecases/get_current_usecase_test.dart' as features_auth_domain_usecases_get_current_usecase_test;
import 'features/auth/domain/usecases/login_usecase_test.dart' as features_auth_domain_usecases_login_usecase_test;
import 'features/auth/domain/usecases/logout_usecase_test.dart' as features_auth_domain_usecases_logout_usecase_test;
import 'features/auth/domain/usecases/register_usecase_test.dart' as features_auth_domain_usecases_register_usecase_test;
import 'features/auth/presentation/pages/login_page_test.dart' as features_auth_presentation_pages_login_page_test;
import 'features/auth/presentation/pages/register_page_test.dart' as features_auth_presentation_pages_register_page_test;
import 'features/auth/presentation/viewmodel/auth_viewmodel_test.dart' as features_auth_presentation_viewmodel_auth_viewmodel_test;
import 'features/booking/domain/initiate_khalti_payment_usecase_test.dart' as features_booking_domain_initiate_khalti_payment_usecase_test;
import 'features/booking/presentation/booking_page_test.dart' as features_booking_presentation_booking_page_test;
import 'features/dashboard/presentation/pages/home_page_test.dart' as features_dashboard_presentation_pages_home_page_test;
import 'features/loyalty/presentation/loyalty_page_test.dart' as features_loyalty_presentation_loyalty_page_test;
import 'features/movies/domain/get_movies_usecase_test.dart' as features_movies_domain_get_movies_usecase_test;
import 'features/movies/presentation/all_movies_page_test.dart' as features_movies_presentation_all_movies_page_test;
import 'features/sales/domain/usecases/get_active_offers_usecase_test.dart' as features_sales_domain_usecases_get_active_offers_usecase_test;
import 'features/sales/presentation/sales_page_test.dart' as features_sales_presentation_sales_page_test;
import 'features/splash/presentation/pages/splash_page_test.dart' as features_splash_presentation_pages_splash_page_test;
import 'features/welcome/presentation/pages/welcome_page_test.dart' as features_welcome_presentation_pages_welcome_page_test;

void main() {
  features_splash_presentation_pages_splash_page_test.main();
  features_sales_domain_usecases_get_active_offers_usecase_test.main();
  features_sales_presentation_sales_page_test.main();
  features_auth_domain_usecases_logout_usecase_test.main();
  features_auth_domain_usecases_get_current_usecase_test.main();
  features_auth_domain_usecases_register_usecase_test.main();
  features_auth_domain_usecases_login_usecase_test.main();
  features_auth_presentation_viewmodel_auth_viewmodel_test.main();
  features_auth_presentation_pages_register_page_test.main();
  features_auth_presentation_pages_login_page_test.main();
  features_booking_domain_initiate_khalti_payment_usecase_test.main();
  features_booking_presentation_booking_page_test.main();
  features_loyalty_presentation_loyalty_page_test.main();
  features_welcome_presentation_pages_welcome_page_test.main();
  features_dashboard_presentation_pages_home_page_test.main();
  features_movies_domain_get_movies_usecase_test.main();
  features_movies_presentation_all_movies_page_test.main();
}
